using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LotR.States
{
    public enum PhaseStep
    {
        None = 0,
        Resource_Start = 101,
        Resource_Add_Resources = 110,
        Resource_Draw_Cards = 120,
        Resource_Player_Actions_Before_End = 198,
        Resource_End = 199,
        Planning_Start = 201,
        Planning_Play_Allies_and_Attachments = 210,
        Planning_Player_Actions_Before_End = 298,
        Planning_End = 299,
        Quest_Start = 301,
        Quest_Player_Actions_Before_Commit_Characters = 309,
        Quest_Commit_Characters = 310,
        Quest_Player_Actions_Before_Staging = 319,
        Quest_Staging = 320,
        Quest_Player_Actions_Before_Quest_Resolution = 329,
        Quest_Quest_Resolution = 330,
        Quest_Player_Actions_Before_End = 398,
        Quest_End = 399,
        Travel_Start = 401,
        Travel_Player_Actions_Before_Traveling = 409,
        Travel_Traveling = 410,
        Travel_Player_Actions_Before_End = 498,
        Travel_End = 499,
        Encounter_Start = 501,
        Encounter_Player_Actions_Before_Optional_Engagement = 509,
        Encounter_Optional_Engagement = 510,
        Encounter_Player_Actions_Before_Engagement_Checks = 519,
        Encounter_Engagement_Checks = 520,
        Encounter_Player_Actions_Before_End = 598,
        Encounter_End = 599,
        Combat_Start = 601,
        Combat_Player_Actions_Before_Chosing_An_Attacking_Enemy = 609,
        Combat_Chose_An_Attacking_Enemy = 610,
        Combat_Player_Actions_Before_Declaring_Defenders = 619,
        Combat_Declaring_Defenders = 620,
        Combat_Player_Actions_Before_Resolve_Shadow_Effects = 629,
        Combat_Resolve_Shadow_Effects = 630,
        Combat_Player_Actions_Before_Determine_Enemy_Combat_Damage = 639,
        Combat_Determine_Enemy_Combat_Damage = 640,
        Combat_Player_Actions_Before_Declaring_Target_Enemy = 649,
        Combat_Declaring_Target_Enemy = 650,
        Combat_Player_Actions_Before_Determining_Character_Attack_Strength = 659,
        Combat_Determining_Character_Attack_Strength = 660,
        Combat_Player_Actions_Before_Determining_Character_Combat_Damage = 669,
        Combat_Determining_Character_Combat_Damage = 670,
        Combat_Player_Actions_Before_End = 698,
        Combat_End = 699,
        Refresh_Start = 701,
        Refresh_Ready_Exhausted_Cards = 710,
        Refresh_Each_Player_Increases_Their_Threat = 720,
        Refresh_First_Player_Changes = 730,
        Refresh_Player_Actions_Before_End = 798,
        Refresh_End = 799,
    }
}
