using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LotR.States
{
    public enum PhaseStep
    {
        None = 0,
        Resource_Start = 101,
        Resource_AddResources = 110,
        Resource_DrawCards = 120,
        Resource_PlayerActionsBeforeEnd = 198,
        Resource_End = 199,
        Planning_Start = 201,
        Planning_PlayAlliesAndAttachments = 210,
        Planning_PlayerActionsBeforeEnd = 298,
        Planning_End = 299,
        Quest_Start = 301,
        Quest_PlayerActionsBeforeCommitCharacters = 309,
        Quest_CommitCharacters = 310,
        Quest_PlayerActionsBeforeStaging = 319,
        Quest_Staging = 320,
        Quest_PlayerActionsBeforeQuestResolution = 329,
        Quest_QuestResolution = 330,
        Quest_PlayerActionsBeforeEnd = 398,
        Quest_End = 399,
        Travel_Start = 401,
        Travel_PlayerActionsBeforeTraveling = 409,
        Travel_Traveling = 410,
        Travel_PlayerActionsBeforeEnd = 498,
        Travel_End = 499,
        Encounter_Start = 501,
        Encounter_PlayerActionsBeforeOptionalEngagement = 509,
        Encounter_OptionalEngagement = 510,
        Encounter_PlayerActionsBeforeEngagementChecks = 519,
        Encounter_EngagementChecks = 520,
        Encounter_Player_Actions_Before_End = 598,
        Encounter_End = 599,
        Combat_Start = 601,
        Combat_PlayerActionsBeforeChosingAnAttackingEnemy = 609,
        Combat_ChoseAnAttackingEnemy = 610,
        Combat_PlayerActionsBeforeDeclareDefenders = 619,
        Combat_DeclareDefenders = 620,
        Combat_PlayerActionsBeforeResolveShadowEffects = 629,
        Combat_ResolveShadowEffects = 630,
        Combat_PlayerActionsBeforeDetermineEnemyCombatDamage = 639,
        Combat_DetermineEnemyCombatDamage = 640,
        Combat_PlayerActionsBeforeDeclareTargetEnemy = 649,
        Combat_DeclareTargetEnemy = 650,
        Combat_PlayerActionsBeforeDetermineCharacterAttackStrength = 659,
        Combat_DetermineCharacterAttackStrength = 660,
        Combat_PlayerActionsBeforeDetermineCharacterCombatDamage = 669,
        Combat_DetermineCharacterCombatDamage = 670,
        Combat_Player_Actions_Before_Combat_End = 698,
        Combat_End = 699,
        Refresh_Start = 701,
        Refresh_Ready_Exhausted_Cards = 710,
        Refresh_Each_Player_Increases_Their_Threat = 720,
        Refresh_First_Player_Changes = 730,
        Refresh_Player_Actions_Before_End = 798,
        Refresh_End = 799,
    }
}
