using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Gnosis.Core.Iso
{
    public class Iso639Language
        : IIso639Language
    {
        private Iso639Language(string alpha3Code, string name)
            : this(alpha3Code, string.Empty, string.Empty, name)
        {
        }

        private Iso639Language(string alpha3Code, string alpha2Code, string name)
            : this(alpha3Code, string.Empty, alpha2Code, name)
        {

        }

        public Iso639Language(string alpha3Code, string alpha3TermCode, string alpha2Code, string name)
        {
            this.alpha3Code = alpha3Code;
            this.alpha3TermCode = alpha3TermCode;
            this.alpha2Code = alpha2Code;
            this.name = name;
        }

        private readonly string alpha3Code;
        private readonly string alpha3TermCode;
        private readonly string alpha2Code;
        private readonly string name;

        #region ILanguage 639 Members

        /// <summary>
        /// The 3-letter alphabetical (Bibliographic) code for ISO 639-2
        /// </summary>
        public string Alpha3Code
        {
            get { return alpha3Code; }
        }

        /// <summary>
        /// The 3-letter alphabetical (Terminology) code for ISO 639-2
        /// </summary>
        /// <remarks>optional - an empty string indicates undefined</remarks>
        public string Alpha3TermCode
        {
            get { return alpha3TermCode; }
        }

        /// <summary>
        /// The 2-letter alphabetical code for ISO 639-1
        /// </summary>
        /// <remarks>optional - an empty string indicates undefined</remarks>
        public string Alpha2Code
        {
            get { return alpha2Code; }
        }

        /// <summary>
        /// The English name of the language
        /// </summary>
        public string Name
        {
            get { return name; }
        }

        #endregion

        private static void InitializeLanguages()
        {
            languages.Add(Afar);
            languages.Add(Abkhazian);
            languages.Add(Achinese);
            languages.Add(Acoli);
            languages.Add(Adangme);
            languages.Add(Adyghe);
            languages.Add(AfroAsiatic);
            languages.Add(Afrihili);
            languages.Add(Afrikaans);
            languages.Add(Ainu);
            languages.Add(Akan);
            languages.Add(Akkadian);
            languages.Add(Albanian);
            languages.Add(Aleut);
            languages.Add(Algonquian);
            languages.Add(SouthernAltai);
            languages.Add(Amharic);
            languages.Add(OldEnglish);
            languages.Add(Angika);
            languages.Add(Apache);
            languages.Add(Arabic);
            languages.Add(Aramaic);
            languages.Add(Aragonese);
            languages.Add(Armenian);
            languages.Add(Mapudungun);
            languages.Add(Arapaho);
            languages.Add(ArtificialLanguages);
            languages.Add(Arawak);
            languages.Add(Assamese);
            languages.Add(Asturian);
            languages.Add(AthapascanLanguages);
            languages.Add(AustrialianLanguages);
            languages.Add(Avaric);
            languages.Add(Avestan);
            languages.Add(Awadhia);
            languages.Add(Aymara);
            languages.Add(Azerbaijani);
            languages.Add(Banda);
            languages.Add(Bamileke);
            languages.Add(Bashkir);
            languages.Add(Baluci);
            languages.Add(Bambara);
            languages.Add(Balinese);
            languages.Add(Basque);
            languages.Add(Basa);
            languages.Add(Baltic);
            languages.Add(Beja);
            languages.Add(Belarusian);
            languages.Add(Bemba);
            languages.Add(Bengali);
            languages.Add(Berber);
            languages.Add(Bhojpuri);
            languages.Add(Bihari);
            languages.Add(Bikol);
            languages.Add(Bini);
            languages.Add(Bislama);
            languages.Add(Siksika);
            languages.Add(Bantu);
            languages.Add(Tibetan);
            languages.Add(Bosnian);
            languages.Add(Braj);
            languages.Add(Breton);
            languages.Add(Batak);
            languages.Add(Buriat);
            languages.Add(Buginese);
            languages.Add(Bulgarian);
            languages.Add(Burmese);
            languages.Add(Bilin);
            languages.Add(Caddo);
            languages.Add(CentralAmericanIndianLanguages);
            languages.Add(Galibi);
            languages.Add(Catalan);
            languages.Add(Caucasian);
            languages.Add(Cebuano);
            languages.Add(Celtic);
            languages.Add(Czech);
            languages.Add(Chamorro);
            languages.Add(Chibcha);
            languages.Add(Chechen);
            languages.Add(Chagatai);
            languages.Add(Chinese);
            languages.Add(Chuukese);
            languages.Add(Mari);
            languages.Add(Chinook);
            languages.Add(Choctaw);
            languages.Add(Chipewyan);
            languages.Add(Cherokee);
            languages.Add(OldBulgarian);
            languages.Add(Chuvash);
            languages.Add(Cheyenne);
            languages.Add(Chamic);
            languages.Add(Coptic);
            languages.Add(Cornish);
            languages.Add(Corsican);
            languages.Add(EnglishCreoles);
            languages.Add(FrenchCreoles);
            languages.Add(PortugueseCreoles);
            languages.Add(Cree);
            languages.Add(CrimeanTatar);
            languages.Add(Creoles);
            languages.Add(Kashubian);
            languages.Add(Cushitic);
            languages.Add(Welsh);
            languages.Add(Dakota);
            languages.Add(Danish);
            languages.Add(Dargwa);
            languages.Add(LandDayak);
            languages.Add(Delaware);
            languages.Add(Slave);
            languages.Add(Dogrib);
            languages.Add(Dinka);
            languages.Add(Divehi);
            languages.Add(Dogri);
            languages.Add(Dravidian);
            languages.Add(LowerSorbian);
            languages.Add(Duala);
            languages.Add(MiddleDutch);
            languages.Add(Dutch);
            languages.Add(Dyula);
            languages.Add(Dzongkha);
            languages.Add(Efik);
            languages.Add(AncientEgyptian);
            languages.Add(Ekajuk);
            languages.Add(Greek);
            languages.Add(Elamite);
            languages.Add(English);
            languages.Add(MiddleEnglish);
            languages.Add(Esperanto);
            languages.Add(Estonian);
            languages.Add(Ewe);
            languages.Add(Ewondo);
            languages.Add(Fang);
            languages.Add(Faroese);
            languages.Add(Persian);
            languages.Add(Fanti);
            languages.Add(Fijian);
            languages.Add(Filipino);
            languages.Add(Finnish);
            languages.Add(FinnoUgurian);
            languages.Add(Fon);
            languages.Add(French);
            languages.Add(MiddleFrench);
            languages.Add(OldFrench);
            languages.Add(NorthernFrisian);
            languages.Add(EasternFrisian);
            languages.Add(WesternFrisian);
            languages.Add(Fulah);
            languages.Add(Friulian);
            languages.Add(Ga);
            languages.Add(Gayo);
            languages.Add(Gbaya);
            languages.Add(GermanicLanguages);
            languages.Add(Georgian);
            languages.Add(German);
            languages.Add(Geez);
            languages.Add(Gilbertese);
            languages.Add(Gaelic);
            languages.Add(Irish);
            languages.Add(Galician);
            languages.Add(Manx);
            languages.Add(MiddleHighGerman);
            languages.Add(OldHighGerman);
            languages.Add(Gondi);
            languages.Add(Gorontalo);
            languages.Add(Gothic);
            languages.Add(Grebo);
            languages.Add(AncientGreek);
            languages.Add(Guarani);
            languages.Add(SwissGerman);
            languages.Add(Gujarati);
            languages.Add(Gwichin);
            languages.Add(Haida);
            languages.Add(Haitian);
            languages.Add(Hausa);
            languages.Add(Hawaiian);
            languages.Add(Hebrew);
            languages.Add(Herero);
            languages.Add(Hiligaynon);
            languages.Add(Himachali);
            languages.Add(Hindi);
            languages.Add(Hittite);
            languages.Add(Hmong);
            languages.Add(HiriMotu);
            languages.Add(Croatian);
            languages.Add(UpperSorbian);
            languages.Add(Hungarian);
            languages.Add(Hupa);
            languages.Add(Iban);
            languages.Add(Igbo);
            languages.Add(Ido);
            languages.Add(SichuanYi);
            languages.Add(Ijo);
            languages.Add(Inuktitut);
            languages.Add(InterlingueOccidental);
            languages.Add(Iloko);
            languages.Add(Interlingua);
            languages.Add(Indic);
            languages.Add(Indonesian);
            languages.Add(IndoEuropean);
            languages.Add(Ingush);
            languages.Add(Inupiaq);
            languages.Add(Iranian);
            languages.Add(Iroquoian);
            languages.Add(Icelandic);
            languages.Add(Italian);
            languages.Add(Javanese);
            languages.Add(Lojban);
            languages.Add(Japanese);
            languages.Add(JudeoPersian);
            languages.Add(JudeoArabic);
            languages.Add(KaraKalpak);
            languages.Add(Kabyle);
            languages.Add(Kachin);
            languages.Add(Kalallisut);
            languages.Add(Kamba);
            languages.Add(Kannada);
            languages.Add(Karen);
            languages.Add(Kashmiri);
            languages.Add(Kanuri);
            languages.Add(Kawi);
            languages.Add(Kazakh);
            languages.Add(Kabardian);
            languages.Add(Khasi);
            languages.Add(Khoisan);
            languages.Add(CentralKhmer);
            languages.Add(Khotanese);
            languages.Add(Kikuyu);
            languages.Add(Kinyarwanda);
            languages.Add(Kirghiz);
            languages.Add(Kimbundu);
            languages.Add(Konkani);
            languages.Add(Komi);
            languages.Add(Kongo);
            languages.Add(Korean);
            languages.Add(Kosraean);
            languages.Add(Kpelle);
            languages.Add(Karachay);
            languages.Add(Karelian);
            languages.Add(Kru);
            languages.Add(Kurukh);
            languages.Add(Kuanyama);
            languages.Add(Kumyk);
            languages.Add(Kurdish);
            languages.Add(Kutenai);
            languages.Add(Ladino);
            languages.Add(Lahnda);
            languages.Add(Lamba);
            languages.Add(Lao);
            languages.Add(Latin);
            languages.Add(Latvian);
            languages.Add(Lezghian);
            languages.Add(Limburgan);
            languages.Add(Lingala);
            languages.Add(Lithuanian);
            languages.Add(Mongo);
            languages.Add(Lozi);
            languages.Add(Luxembourgish);
            languages.Add(LubaLulua);
            languages.Add(LubaKatanga);
            languages.Add(Ganda);
            languages.Add(Luiseno);
            languages.Add(Lunda);
            languages.Add(Luo);
            languages.Add(Lushai);
            languages.Add(Macedonian);
            languages.Add(Madurese);
            languages.Add(Magahi);
            languages.Add(Marshallese);
            languages.Add(Maithili);
            languages.Add(Makasar);
            languages.Add(Malayalam);
            languages.Add(Mandingo);
            languages.Add(Maori);
            languages.Add(Austronesian);
            languages.Add(Marathi);
            languages.Add(Masai);
            languages.Add(Malay);
            languages.Add(Moksha);
            languages.Add(Mandar);
            languages.Add(Mende);
            languages.Add(MiddleIrish);
            languages.Add(Micmac);
            languages.Add(Minangkabau);
            languages.Add(UncodedLanguages);
            languages.Add(MonKhmer);
            languages.Add(Malagasy);
            languages.Add(Maltese);
            languages.Add(Manchu);
            languages.Add(Manipuri);
            languages.Add(Manobo);
            languages.Add(Mohawk);
            languages.Add(Mongolian);
            languages.Add(Mossi);
            languages.Add(MultipleLanguages);
            languages.Add(MundaLanguages);
            languages.Add(Creek);
            languages.Add(Mirandese);
            languages.Add(Marwari);
            languages.Add(Mayan);
            languages.Add(Erzya);
            languages.Add(Nahuatl);
            languages.Add(NorthAmericanIndian);
            languages.Add(Neapolitan);
            languages.Add(Nauru);
            languages.Add(Navajo);
            languages.Add(SouthNdebele);
            languages.Add(NorthNdebele);
            languages.Add(Ndonga);
            languages.Add(LowGerman);
            languages.Add(Nepali);
            languages.Add(NepalBhasa);
            languages.Add(Nias);
            languages.Add(NigerKordofanian);
            languages.Add(Niuean);
            languages.Add(NorwegianNynorsk);
            languages.Add(NorwegianBokmal);
            languages.Add(Nogai);
            languages.Add(OldNorse);
            languages.Add(Norwegian);
            languages.Add(NKo);
            languages.Add(Pedi);
            languages.Add(Nubian);
            languages.Add(ClassicalNewari);
            languages.Add(Chichewa);
            languages.Add(Nyamwezi);
            languages.Add(Nyankole);
            languages.Add(Nyoro);
            languages.Add(Nzima);
            languages.Add(Occitan);
            languages.Add(Ojibway);
            languages.Add(Oriya);
            languages.Add(Oromo);
            languages.Add(Osage);
            languages.Add(Ossetian);
            languages.Add(OttomanTurkish);
            languages.Add(Otomian);
            languages.Add(Papuan);
            languages.Add(Pangasinan);
            languages.Add(Pahlavi);
            languages.Add(Pampanga);
            languages.Add(Panjabi);
            languages.Add(Papiamento);
            languages.Add(Palauan);
            languages.Add(OldPersian);
            languages.Add(PhilippineLanguages);
            languages.Add(Phoenician);
            languages.Add(Pali);
            languages.Add(Polish);
            languages.Add(Pohnpeian);
            languages.Add(Portuguese);
            languages.Add(Prakrit);
            languages.Add(OldProvencal);
            languages.Add(Pushto);
            languages.Add(Quechua);
            languages.Add(Rajasthani);
            languages.Add(Rapanui);
            languages.Add(Rarotongan);
            languages.Add(RomanceLanguages);
            languages.Add(Romansh);
            languages.Add(Romany);
            languages.Add(Romanian);
            languages.Add(Rundi);
            languages.Add(Aromanian);
            languages.Add(Russian);
            languages.Add(Sandawe);
            languages.Add(Sango);
            languages.Add(Yakut);
            languages.Add(SouthAmericanIndianLanguages);
            languages.Add(Salishan);
            languages.Add(SamaritanAramaic);
            languages.Add(Sanskrit);
            languages.Add(Sasak);
            languages.Add(Santali);
            languages.Add(Sicilian);
            languages.Add(Scots);
            languages.Add(Selkup);
            languages.Add(Semitic);
            languages.Add(OldIrish);
            languages.Add(SignLanguages);
            languages.Add(Shan);
            languages.Add(Sidamo);
            languages.Add(Sinhala);
            languages.Add(Siouan);
            languages.Add(SinoTibetan);
            languages.Add(Slavic);
            languages.Add(Slovak);
            languages.Add(Slovenian);
            languages.Add(SouthernSami);
            languages.Add(NorthernSami);
            languages.Add(SamiLanguages);
            languages.Add(LuleSami);
            languages.Add(InariSami);
            languages.Add(Samoan);
            languages.Add(SkoltSami);
            languages.Add(Shona);
            languages.Add(Sindhi);
            languages.Add(Sonike);
            languages.Add(Sogdian);
            languages.Add(Somali);
            languages.Add(Songhai);
            languages.Add(Sotho);
            languages.Add(Spanish);
            languages.Add(Sardinian);
            languages.Add(Sranan);
            languages.Add(Serbian);
            languages.Add(Serer);
            languages.Add(NiloSaharan);
            languages.Add(Swati);
            languages.Add(Sukuma);
            languages.Add(Sudanese);
            languages.Add(Susu);
            languages.Add(Sumerian);
            languages.Add(Swahili);
            languages.Add(Swedish);
            languages.Add(ClassicalSyriac);
            languages.Add(Syriac);
            languages.Add(Tahitian);
            languages.Add(TaiLanguages);
            languages.Add(Tamil);
            languages.Add(Tatar);
            languages.Add(Teluga);
            languages.Add(Timne);
            languages.Add(Tereno);
            languages.Add(Tetum);
            languages.Add(Tajik);
            languages.Add(Tagalog);
            languages.Add(Thai);
            languages.Add(Tigre);
            languages.Add(Tigrinya);
            languages.Add(Tiv);
            languages.Add(Tokelau);
            languages.Add(Klingon);
            languages.Add(Tlingit);
            languages.Add(Tamashek);
            languages.Add(TongaNyasa);
            languages.Add(Tonga);
            languages.Add(TokPisin);
            languages.Add(Tsimshian);
            languages.Add(Tswana);
            languages.Add(Tsonga);
            languages.Add(Turkmen);
            languages.Add(Tumbuka);
            languages.Add(Tupi);
            languages.Add(Turkish);
            languages.Add(Altaic);
            languages.Add(Tuvalu);
            languages.Add(Twi);
            languages.Add(Tuvian);
            languages.Add(Udmurt);
            languages.Add(Ugaritic);
            languages.Add(Uighur);
            languages.Add(Ukrainian);
            languages.Add(Umbundu);
            languages.Add(Undetermined);
            languages.Add(Urdu);
            languages.Add(Uzbek);
            languages.Add(Vai);
            languages.Add(Venda);
            languages.Add(Vietnamese);
            languages.Add(Volapuk);
            languages.Add(Votic);
            languages.Add(Wakashan);
            languages.Add(Walaitta);
            languages.Add(Waray);
            languages.Add(Washo);
            languages.Add(Sorbian);
            languages.Add(Walloon);
            languages.Add(Wolof);
            languages.Add(Kalmyk);
            languages.Add(Xhosa);
            languages.Add(Yao);
            languages.Add(Yapese);
            languages.Add(Yiddish);
            languages.Add(Yor);
            languages.Add(Yupik);
            languages.Add(Zapotec);
            languages.Add(Bliss);
            languages.Add(Zenaga);
            languages.Add(Zhuang);
            languages.Add(Zande);
            languages.Add(Zulu);
            languages.Add(Zuni);
            languages.Add(NotApplicable);
            languages.Add(Zaza);
        }

        static Iso639Language()
        {
            InitializeLanguages();

            foreach (var language in languages)
            {
                if (!string.IsNullOrEmpty(language.Alpha2Code))
                    byAlpha2Code.Add(language.Alpha2Code, language);

                if (!string.IsNullOrEmpty(language.Alpha3TermCode))
                    byAlpha3TermCode.Add(language.Alpha3TermCode, language);

                byAlpha3Code.Add(language.Alpha3Code, language);
                byName.Add(language.Name, language);
            }
        }

        private static readonly IList<IIso639Language> languages = new List<IIso639Language>();
        private static readonly IDictionary<string, IIso639Language> byAlpha2Code = new Dictionary<string, IIso639Language>();
        private static readonly IDictionary<string, IIso639Language> byAlpha3Code = new Dictionary<string, IIso639Language>();
        private static readonly IDictionary<string, IIso639Language> byAlpha3TermCode = new Dictionary<string, IIso639Language>();
        private static readonly IDictionary<string, IIso639Language> byName = new Dictionary<string, IIso639Language>();

        #region Public Static Members

        public static IIso639Language GetLanguageByCode(string code)
        {
            if (byAlpha2Code.ContainsKey(code))
                return byAlpha2Code[code];

            if (byAlpha3TermCode.ContainsKey(code))
                return byAlpha3TermCode[code];

            return byAlpha3Code.ContainsKey(code) ? byAlpha3Code[code] : Iso639Language.Undetermined;
        }

        public static IIso639Language GetLanguageByName(string name)
        {
            return byName.ContainsKey(name) ? byName[name] : Iso639Language.Undetermined;
        }

        public static IEnumerable<IIso639Language> GetLanguages()
        {
            return languages;
        }

        #endregion

        #region Languages

        public static readonly Iso639Language Afar = new Iso639Language("aar", "aa", "Afar");
        public static readonly Iso639Language Abkhazian = new Iso639Language("abk", "ab", "Abkhazian");
        public static readonly Iso639Language Achinese = new Iso639Language("ace", "Achinese");
        public static readonly Iso639Language Acoli = new Iso639Language("ach","Acoli");
        public static readonly Iso639Language Adangme = new Iso639Language("ada","Adangme");
        public static readonly Iso639Language Adyghe = new Iso639Language("ady","Adyghe; Adygei");
        public static readonly Iso639Language AfroAsiatic = new Iso639Language("afa","Afro-Asiatic languages");
        public static readonly Iso639Language Afrihili = new Iso639Language("afh","Afrihili");
        public static readonly Iso639Language Afrikaans = new Iso639Language("afr","af","Afrikaans");
        public static readonly Iso639Language Ainu = new Iso639Language("ain","Ainu");
        public static readonly Iso639Language Akan = new Iso639Language("aka","ak","Akan");
        public static readonly Iso639Language Akkadian = new Iso639Language("akk","Akkadian");
        public static readonly Iso639Language Albanian = new Iso639Language("alb", "sqi", "sq", "Albanian");
        public static readonly Iso639Language Aleut = new Iso639Language("ale","Aleut");
        public static readonly Iso639Language Algonquian = new Iso639Language("alg","Algonquian languages");
        public static readonly Iso639Language SouthernAltai = new Iso639Language("alt","Southern Altai");
        public static readonly Iso639Language Amharic = new Iso639Language("amh","am","Amharic");
        public static readonly Iso639Language OldEnglish = new Iso639Language("ang", "English, Old (ca.450-1100)");
        public static readonly Iso639Language Angika = new Iso639Language("anp","Angika");
        public static readonly Iso639Language Apache = new Iso639Language("apa","Apache languages");
        public static readonly Iso639Language Arabic = new Iso639Language("ara","ar","Arabic");
        public static readonly Iso639Language Aramaic = new Iso639Language("arc","Official Aramaic (700-300 BCE)");
        public static readonly Iso639Language Aragonese = new Iso639Language("arg","an","Aragonese");
        public static readonly Iso639Language Armenian = new Iso639Language("arm", "hye", "hy", "Armenian");
        public static readonly Iso639Language Mapudungun = new Iso639Language("arn","Mapudungun; Mapuche");
        public static readonly Iso639Language Arapaho = new Iso639Language("arp","Arapaho");
        public static readonly Iso639Language ArtificialLanguages = new Iso639Language("art","Artificial languages");
        public static readonly Iso639Language Arawak = new Iso639Language("arw","Arawak");
        public static readonly Iso639Language Assamese = new Iso639Language("asm","as","Assamese");
        public static readonly Iso639Language Asturian = new Iso639Language("ast","Asturian; Bable; Leonese; Asturleonese");
        public static readonly Iso639Language AthapascanLanguages = new Iso639Language("ath","Athapascan languages");
        public static readonly Iso639Language AustrialianLanguages = new Iso639Language("aus","Australian languages");
        public static readonly Iso639Language Avaric = new Iso639Language("ava","av","Avaric");
        public static readonly Iso639Language Avestan = new Iso639Language("ave","ae","Avestan");
        public static readonly Iso639Language Awadhia = new Iso639Language("awa","Awadhi");
        public static readonly Iso639Language Aymara = new Iso639Language("aym","ay","Aymara");
        public static readonly Iso639Language Azerbaijani = new Iso639Language("aze","az","Azerbaijani");
        public static readonly Iso639Language Banda = new Iso639Language("bad","Banda languages");
        public static readonly Iso639Language Bamileke = new Iso639Language("bai","Bamileke languages");
        public static readonly Iso639Language Bashkir = new Iso639Language("bak","ba","Bashkir");
        public static readonly Iso639Language Baluci = new Iso639Language("bal","Baluchi");
        public static readonly Iso639Language Bambara = new Iso639Language("bam","bm","Bambara");
        public static readonly Iso639Language Balinese = new Iso639Language("ban","Balinese");
        public static readonly Iso639Language Basque = new Iso639Language("baq", "eus", "eu", "Basque");
        public static readonly Iso639Language Basa = new Iso639Language("bas","Basa");
        public static readonly Iso639Language Baltic = new Iso639Language("bat","Baltic languages");
        public static readonly Iso639Language Beja = new Iso639Language("bej","Beja; Bedawiyet");
        public static readonly Iso639Language Belarusian = new Iso639Language("bel","be","Belarusian");
        public static readonly Iso639Language Bemba = new Iso639Language("bem","Bemba");
        public static readonly Iso639Language Bengali = new Iso639Language("ben","bn","Bengali");
        public static readonly Iso639Language Berber = new Iso639Language("ber","Berber languages");
        public static readonly Iso639Language Bhojpuri = new Iso639Language("bho","Bhojpuri");
        public static readonly Iso639Language Bihari = new Iso639Language("bih","bh","Bihari languages");
        public static readonly Iso639Language Bikol = new Iso639Language("bik","Bikol");
        public static readonly Iso639Language Bini = new Iso639Language("bin","Bini; Edo");
        public static readonly Iso639Language Bislama = new Iso639Language("bis","bi","Bislama");
        public static readonly Iso639Language Siksika = new Iso639Language("bla","Siksika");
        public static readonly Iso639Language Bantu = new Iso639Language("bnt","Bantu languages");
        public static readonly Iso639Language Tibetan = new Iso639Language("tib", "bod", "bo","Tibetan");
        public static readonly Iso639Language Bosnian = new Iso639Language("bos","bs","Bosnian");
        public static readonly Iso639Language Braj = new Iso639Language("bra","Braj");
        public static readonly Iso639Language Breton = new Iso639Language("bre","br","Breton");
        public static readonly Iso639Language Batak = new Iso639Language("btk	","Batak languages");
        public static readonly Iso639Language Buriat = new Iso639Language("bua","Buriat");
        public static readonly Iso639Language Buginese = new Iso639Language("bug","Buginese");
        public static readonly Iso639Language Bulgarian = new Iso639Language("bul","bg","Bulgarian");
        public static readonly Iso639Language Burmese = new Iso639Language("bur","mya", "my",	"Burmese");
        public static readonly Iso639Language Bilin = new Iso639Language("byn","Blin; Bilin");
        public static readonly Iso639Language Caddo = new Iso639Language("cad","Caddo");
        public static readonly Iso639Language CentralAmericanIndianLanguages = new Iso639Language("cai","Central American Indian languages");
        public static readonly Iso639Language Galibi = new Iso639Language("car","Galibi Carib");
        public static readonly Iso639Language Catalan = new Iso639Language("cat","ca","Catalan; Valencian");
        public static readonly Iso639Language Caucasian = new Iso639Language("cau","Caucasian languages");
        public static readonly Iso639Language Cebuano = new Iso639Language("ceb","Cebuano");
        public static readonly Iso639Language Celtic = new Iso639Language("cel","Celtic languages");
        public static readonly Iso639Language Czech = new Iso639Language("cze", "ces", "cs", "Czech");
        public static readonly Iso639Language Chamorro = new Iso639Language("cha","ch","Chamorro");
        public static readonly Iso639Language Chibcha = new Iso639Language("chb","Chibcha");
        public static readonly Iso639Language Chechen = new Iso639Language("che","ce","Chechen");
        public static readonly Iso639Language Chagatai = new Iso639Language("chg","Chagatai");
        public static readonly Iso639Language Chinese = new Iso639Language("chi", "zho","zh","Chinese");
        public static readonly Iso639Language Chuukese = new Iso639Language("chk","Chuukese");
        public static readonly Iso639Language Mari = new Iso639Language("chm","Mari");
        public static readonly Iso639Language Chinook = new Iso639Language("chn","Chinook jargon");
        public static readonly Iso639Language Choctaw = new Iso639Language("cho","Choctaw");
        public static readonly Iso639Language Chipewyan = new Iso639Language("chp","Chipewyan; Dene Suline");
        public static readonly Iso639Language Cherokee = new Iso639Language("chr","Cherokee");
        public static readonly Iso639Language OldBulgarian = new Iso639Language("chu","cu","Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic");
        public static readonly Iso639Language Chuvash = new Iso639Language("chv","cv","Chuvash");
        public static readonly Iso639Language Cheyenne = new Iso639Language("chy","Cheyenne");
        public static readonly Iso639Language Chamic = new Iso639Language("cmc","Chamic languages");
        public static readonly Iso639Language Coptic = new Iso639Language("cop","Coptic");
        public static readonly Iso639Language Cornish = new Iso639Language("cor","kw","Cornish");
        public static readonly Iso639Language Corsican = new Iso639Language("cos","co","Corsican");
        public static readonly Iso639Language EnglishCreoles = new Iso639Language("cpe","Creoles and pidgins, English based");
        public static readonly Iso639Language FrenchCreoles = new Iso639Language("cpf","Creoles and pidgins, French-based");
        public static readonly Iso639Language PortugueseCreoles = new Iso639Language("cpp","Creoles and pidgins, Portuguese-based");
        public static readonly Iso639Language Cree = new Iso639Language("cre","cr","Cree");
        public static readonly Iso639Language CrimeanTatar = new Iso639Language("crh","Crimean Tatar; Crimean Turkish");
        public static readonly Iso639Language Creoles = new Iso639Language("crp","Creoles and pidgins");
        public static readonly Iso639Language Kashubian = new Iso639Language("csb","Kashubian");
        public static readonly Iso639Language Cushitic = new Iso639Language("cus","Cushitic languages");
        public static readonly Iso639Language Welsh = new Iso639Language("wel", "cym","cy","Welsh");
        public static readonly Iso639Language Dakota = new Iso639Language("dak","Dakota");
        public static readonly Iso639Language Danish = new Iso639Language("dan","da","Danish");
        public static readonly Iso639Language Dargwa = new Iso639Language("dar","Dargwa");
        public static readonly Iso639Language LandDayak = new Iso639Language("day","Land Dayak languages");
        public static readonly Iso639Language Delaware = new Iso639Language("del","Delaware");
        public static readonly Iso639Language Slave = new Iso639Language("den","Slave (Athapascan)");
        public static readonly Iso639Language Dogrib = new Iso639Language("dgr","Dogrib");
        public static readonly Iso639Language Dinka = new Iso639Language("din","Dinka");
        public static readonly Iso639Language Divehi = new Iso639Language("div","dv","Divehi; Dhivehi; Maldivian");
        public static readonly Iso639Language Dogri = new Iso639Language("doi","Dogri");
        public static readonly Iso639Language Dravidian = new Iso639Language("dra","Dravidian languages");
        public static readonly Iso639Language LowerSorbian = new Iso639Language("dsb","Lower Sorbian");
        public static readonly Iso639Language Duala = new Iso639Language("dua","Duala");
        public static readonly Iso639Language MiddleDutch = new Iso639Language("dum","Dutch, Middle (ca.1050-1350)");
        public static readonly Iso639Language Dutch = new Iso639Language("dut", "nld", "nl", "Dutch; Flemish");
        public static readonly Iso639Language Dyula = new Iso639Language("dyu","Dyula");
        public static readonly Iso639Language Dzongkha = new Iso639Language("dzo","dz","Dzongkha");
        public static readonly Iso639Language Efik = new Iso639Language("efi","Efik");
        public static readonly Iso639Language AncientEgyptian = new Iso639Language("egy","Egyptian (Ancient)");
        public static readonly Iso639Language Ekajuk = new Iso639Language("eka","Ekajuk");
        public static readonly Iso639Language Greek = new Iso639Language("gre", "ell", "el", "Greek, Modern (1453-)");
        public static readonly Iso639Language Elamite = new Iso639Language("elx","Elamite");
        public static readonly Iso639Language English = new Iso639Language("eng","en","English");
        public static readonly Iso639Language MiddleEnglish = new Iso639Language("enm","English, Middle (1100-1500)");
        public static readonly Iso639Language Esperanto = new Iso639Language("epo","eo","Esperanto");
        public static readonly Iso639Language Estonian = new Iso639Language("est","et","Estonian");
        public static readonly Iso639Language Ewe = new Iso639Language("ewe","ee","Ewe");
        public static readonly Iso639Language Ewondo = new Iso639Language("ewo","Ewondo");
        public static readonly Iso639Language Fang = new Iso639Language("fan","Fang");
        public static readonly Iso639Language Faroese = new Iso639Language("fao","fo","Faroese");
        public static readonly Iso639Language Persian = new Iso639Language("per", "fas", "fa", "Persian");
        public static readonly Iso639Language Fanti = new Iso639Language("fat","Fanti");
        public static readonly Iso639Language Fijian = new Iso639Language("fij","fj","Fijian");
        public static readonly Iso639Language Filipino = new Iso639Language("fil","Filipino; Pilipino");
        public static readonly Iso639Language Finnish = new Iso639Language("fin","fi","Finnish");
        public static readonly Iso639Language FinnoUgurian = new Iso639Language("fiu","Finno-Ugrian languages");
        public static readonly Iso639Language Fon = new Iso639Language("fon","Fon");
        public static readonly Iso639Language French = new Iso639Language("fre", "fra", "fr", "French");
        public static readonly Iso639Language MiddleFrench = new Iso639Language("frm","French, Middle (ca.1400-1600)");
        public static readonly Iso639Language OldFrench = new Iso639Language("fro","French, Old (842-ca.1400)");
        public static readonly Iso639Language NorthernFrisian = new Iso639Language("frr","Northern Frisian");
        public static readonly Iso639Language EasternFrisian = new Iso639Language("frs","Eastern Frisian");
        public static readonly Iso639Language WesternFrisian = new Iso639Language("fry","fy","Western Frisian");
        public static readonly Iso639Language Fulah = new Iso639Language("ful","ff","Fulah");
        public static readonly Iso639Language Friulian = new Iso639Language("fur","Friulian");
        public static readonly Iso639Language Ga = new Iso639Language("gaa","Ga");
        public static readonly Iso639Language Gayo = new Iso639Language("gay","Gayo");
        public static readonly Iso639Language Gbaya = new Iso639Language("gba","Gbaya");
        public static readonly Iso639Language GermanicLanguages = new Iso639Language("gem", "Germanic languages");
        public static readonly Iso639Language Georgian = new Iso639Language("geo", "kat", "ka", "Georgian");
        public static readonly Iso639Language German = new Iso639Language("ger", "deu", "de", "German");
        public static readonly Iso639Language Geez = new Iso639Language("gez","Geez");
        public static readonly Iso639Language Gilbertese = new Iso639Language("gil","Gilbertese");
        public static readonly Iso639Language Gaelic = new Iso639Language("gla","gd","Gaelic; Scottish Gaelic");
        public static readonly Iso639Language Irish = new Iso639Language("gle","ga","Irish");
        public static readonly Iso639Language Galician = new Iso639Language("glg","gl","Galician");
        public static readonly Iso639Language Manx = new Iso639Language("glv","gv","Manx");
        public static readonly Iso639Language MiddleHighGerman = new Iso639Language("gmh","German, Middle High (ca.1050-1500)");
        public static readonly Iso639Language OldHighGerman = new Iso639Language("goh","German, Old High (ca.750-1050)");
        public static readonly Iso639Language Gondi = new Iso639Language("gon","Gondi");
        public static readonly Iso639Language Gorontalo = new Iso639Language("gor","Gorontalo");
        public static readonly Iso639Language Gothic = new Iso639Language("got","Gothic");
        public static readonly Iso639Language Grebo = new Iso639Language("grb","Grebo");
        public static readonly Iso639Language AncientGreek = new Iso639Language("grc","Greek, Ancient (to 1453)");
        public static readonly Iso639Language Guarani = new Iso639Language("grn","gn","Guarani");
        public static readonly Iso639Language SwissGerman = new Iso639Language("gsw","Swiss German; Alemannic; Alsatian");
        public static readonly Iso639Language Gujarati = new Iso639Language("guj","gu","Gujarati");
        public static readonly Iso639Language Gwichin = new Iso639Language("gwi","Gwich'in");
        public static readonly Iso639Language Haida = new Iso639Language("hai","Haida");
        public static readonly Iso639Language Haitian = new Iso639Language("hat","ht","Haitian; Haitian Creole");
        public static readonly Iso639Language Hausa = new Iso639Language("hau","ha","Hausa");
        public static readonly Iso639Language Hawaiian = new Iso639Language("haw","Hawaiian");
        public static readonly Iso639Language Hebrew = new Iso639Language("heb","he","Hebrew");
        public static readonly Iso639Language Herero = new Iso639Language("her","hz","Herero");
        public static readonly Iso639Language Hiligaynon = new Iso639Language("hil","Hiligaynon");
        public static readonly Iso639Language Himachali = new Iso639Language("him","Himachali languages; Western Pahari languages");
        public static readonly Iso639Language Hindi = new Iso639Language("hin","hi","Hindi");
        public static readonly Iso639Language Hittite = new Iso639Language("hit","Hittite");
        public static readonly Iso639Language Hmong = new Iso639Language("hmn","Hmong; Mong");
        public static readonly Iso639Language HiriMotu = new Iso639Language("hmo","ho","Hiri Motu");
        public static readonly Iso639Language Croatian = new Iso639Language("hrv","hr","Croatian");
        public static readonly Iso639Language UpperSorbian = new Iso639Language("hsb","Upper Sorbian");
        public static readonly Iso639Language Hungarian = new Iso639Language("hun","hu","Hungarian");
        public static readonly Iso639Language Hupa = new Iso639Language("hup","Hupa");
        public static readonly Iso639Language Iban = new Iso639Language("iba","Iban");
        public static readonly Iso639Language Igbo = new Iso639Language("ibo","ig","Igbo");
        public static readonly Iso639Language Ido = new Iso639Language("ido","io","Ido");
        public static readonly Iso639Language SichuanYi = new Iso639Language("iii","ii","Sichuan Yi; Nuosu");
        public static readonly Iso639Language Ijo = new Iso639Language("ijo","Ijo languages");
        public static readonly Iso639Language Inuktitut = new Iso639Language("iku","iu","Inuktitut");
        public static readonly Iso639Language InterlingueOccidental = new Iso639Language("ile","ie","Interlingue; Occidental");
        public static readonly Iso639Language Iloko = new Iso639Language("ilo","Iloko");
        public static readonly Iso639Language Interlingua = new Iso639Language("ina","ia","Interlingua (International Auxiliary Language Association)");
        public static readonly Iso639Language Indic = new Iso639Language("inc","Indic languages");
        public static readonly Iso639Language Indonesian = new Iso639Language("ind","id","Indonesian");
        public static readonly Iso639Language IndoEuropean = new Iso639Language("ine","Indo-European languages");
        public static readonly Iso639Language Ingush = new Iso639Language("inh","Ingush");
        public static readonly Iso639Language Inupiaq = new Iso639Language("ipk","ik","Inupiaq");
        public static readonly Iso639Language Iranian = new Iso639Language("ira","Iranian languages");
        public static readonly Iso639Language Iroquoian = new Iso639Language("iro","Iroquoian languages");
        public static readonly Iso639Language Icelandic = new Iso639Language("ice","isl","is","Icelandic");
        public static readonly Iso639Language Italian = new Iso639Language("ita","it","Italian");
        public static readonly Iso639Language Javanese = new Iso639Language("jav","jv","Javanese");
        public static readonly Iso639Language Lojban = new Iso639Language("jbo","Lojban");
        public static readonly Iso639Language Japanese = new Iso639Language("jpn","ja","Japanese");
        public static readonly Iso639Language JudeoPersian = new Iso639Language("jpr","Judeo-Persian");
        public static readonly Iso639Language JudeoArabic = new Iso639Language("jrb","Judeo-Arabic");
        public static readonly Iso639Language KaraKalpak = new Iso639Language("kaa","Kara-Kalpak");
        public static readonly Iso639Language Kabyle = new Iso639Language("kab","Kabyle");
        public static readonly Iso639Language Kachin = new Iso639Language("kac","Kachin; Jingpho");
        public static readonly Iso639Language Kalallisut = new Iso639Language("kal","kl","Kalaallisut; Greenlandic");
        public static readonly Iso639Language Kamba = new Iso639Language("kam","Kamba");
        public static readonly Iso639Language Kannada = new Iso639Language("kan","kn","Kannada");
        public static readonly Iso639Language Karen = new Iso639Language("kar","Karen languages");
        public static readonly Iso639Language Kashmiri = new Iso639Language("kas","ks","Kashmiri");
        public static readonly Iso639Language Kanuri = new Iso639Language("kau","kr","Kanuri");
        public static readonly Iso639Language Kawi = new Iso639Language("kaw","Kawi");
        public static readonly Iso639Language Kazakh = new Iso639Language("kaz","kk","Kazakh");
        public static readonly Iso639Language Kabardian = new Iso639Language("kbd","Kabardian");
        public static readonly Iso639Language Khasi = new Iso639Language("kha","Khasi");
        public static readonly Iso639Language Khoisan = new Iso639Language("khi","Khoisan languages");
        public static readonly Iso639Language CentralKhmer = new Iso639Language("khm","km","Central Khmer");
        public static readonly Iso639Language Khotanese = new Iso639Language("kho","Khotanese; Sakan");
        public static readonly Iso639Language Kikuyu = new Iso639Language("kik","ki","Kikuyu; Gikuyu");
        public static readonly Iso639Language Kinyarwanda = new Iso639Language("kin","rw","Kinyarwanda");
        public static readonly Iso639Language Kirghiz = new Iso639Language("kir","ky","Kirghiz; Kyrgyz");
        public static readonly Iso639Language Kimbundu = new Iso639Language("kmb","Kimbundu");
        public static readonly Iso639Language Konkani = new Iso639Language("kok","Konkani");
        public static readonly Iso639Language Komi = new Iso639Language("kom","kv","Komi");
        public static readonly Iso639Language Kongo = new Iso639Language("kon","kg","Kongo");
        public static readonly Iso639Language Korean = new Iso639Language("kor","ko","Korean");
        public static readonly Iso639Language Kosraean = new Iso639Language("kos","Kosraean");
        public static readonly Iso639Language Kpelle = new Iso639Language("kpe","Kpelle");
        public static readonly Iso639Language Karachay = new Iso639Language("krc","Karachay-Balkar");
        public static readonly Iso639Language Karelian = new Iso639Language("krl","Karelian");
        public static readonly Iso639Language Kru = new Iso639Language("kro","Kru languages");
        public static readonly Iso639Language Kurukh = new Iso639Language("kru","Kurukh");
        public static readonly Iso639Language Kuanyama = new Iso639Language("kua","kj","Kuanyama; Kwanyama");
        public static readonly Iso639Language Kumyk = new Iso639Language("kum","Kumyk");
        public static readonly Iso639Language Kurdish = new Iso639Language("kur","ku","Kurdish");
        public static readonly Iso639Language Kutenai = new Iso639Language("kut","Kutenai");
        public static readonly Iso639Language Ladino = new Iso639Language("lad","Ladino");
        public static readonly Iso639Language Lahnda = new Iso639Language("lah","Lahnda");
        public static readonly Iso639Language Lamba = new Iso639Language("lam","Lamba");
        public static readonly Iso639Language Lao = new Iso639Language("lao","lo","Lao");
        public static readonly Iso639Language Latin = new Iso639Language("lat","la","Latin");
        public static readonly Iso639Language Latvian = new Iso639Language("lav","lv","Latvian");
        public static readonly Iso639Language Lezghian = new Iso639Language("lez","Lezghian");
        public static readonly Iso639Language Limburgan = new Iso639Language("lim","li","Limburgan; Limburger; Limburgish");
        public static readonly Iso639Language Lingala = new Iso639Language("lin","ln","Lingala");
        public static readonly Iso639Language Lithuanian = new Iso639Language("lit","lt","Lithuanian");
        public static readonly Iso639Language Mongo = new Iso639Language("lol","Mongo");
        public static readonly Iso639Language Lozi = new Iso639Language("loz","Lozi");
        public static readonly Iso639Language Luxembourgish = new Iso639Language("ltz","lb","Luxembourgish; Letzeburgesch");
        public static readonly Iso639Language LubaLulua = new Iso639Language("lua","Luba-Lulua");
        public static readonly Iso639Language LubaKatanga = new Iso639Language("lub","lu","Luba-Katanga");
        public static readonly Iso639Language Ganda = new Iso639Language("lug","lg","Ganda");
        public static readonly Iso639Language Luiseno = new Iso639Language("lui","Luiseno");
        public static readonly Iso639Language Lunda = new Iso639Language("lun","Lunda");
        public static readonly Iso639Language Luo = new Iso639Language("luo","Luo (Kenya and Tanzania)");
        public static readonly Iso639Language Lushai = new Iso639Language("lus","Lushai");
        public static readonly Iso639Language Macedonian = new Iso639Language("mac","mkd","mk","Macedonian");
        public static readonly Iso639Language Madurese = new Iso639Language("mad","Madurese");
        public static readonly Iso639Language Magahi = new Iso639Language("mag","Magahi");
        public static readonly Iso639Language Marshallese = new Iso639Language("mah","mh","Marshallese");
        public static readonly Iso639Language Maithili = new Iso639Language("mai","Maithili");
        public static readonly Iso639Language Makasar = new Iso639Language("mak","Makasar");
        public static readonly Iso639Language Malayalam = new Iso639Language("mal","ml","Malayalam");
        public static readonly Iso639Language Mandingo = new Iso639Language("man","Mandingo");
        public static readonly Iso639Language Maori = new Iso639Language("mao","mri","mi","Maori");
        public static readonly Iso639Language Austronesian = new Iso639Language("map","Austronesian languages");
        public static readonly Iso639Language Marathi = new Iso639Language("mar","mr","Marathi");
        public static readonly Iso639Language Masai = new Iso639Language("mas","Masai");
        public static readonly Iso639Language Malay = new Iso639Language("may","msa","ms","Malay");
        public static readonly Iso639Language Moksha = new Iso639Language("mdf","Moksha");
        public static readonly Iso639Language Mandar = new Iso639Language("mdr","Mandar");
        public static readonly Iso639Language Mende = new Iso639Language("men","Mende");
        public static readonly Iso639Language MiddleIrish = new Iso639Language("mga","Irish, Middle (900-1200)");
        public static readonly Iso639Language Micmac = new Iso639Language("mic","Mi'kmaq; Micmac");
        public static readonly Iso639Language Minangkabau = new Iso639Language("min","Minangkabau");
        public static readonly Iso639Language UncodedLanguages = new Iso639Language("mis","Uncoded languages");
        public static readonly Iso639Language MonKhmer = new Iso639Language("mkh","Mon-Khmer languages");
        public static readonly Iso639Language Malagasy = new Iso639Language("mlg","mg","Malagasy");
        public static readonly Iso639Language Maltese = new Iso639Language("mlt","mt","Maltese");
        public static readonly Iso639Language Manchu = new Iso639Language("mnc","Manchu");
        public static readonly Iso639Language Manipuri = new Iso639Language("mni","Manipuri");
        public static readonly Iso639Language Manobo = new Iso639Language("mno","Manobo languages");
        public static readonly Iso639Language Mohawk = new Iso639Language("moh","Mohawk");
        public static readonly Iso639Language Mongolian = new Iso639Language("mon","mn","Mongolian");
        public static readonly Iso639Language Mossi = new Iso639Language("mos","Mossi");
        public static readonly Iso639Language MultipleLanguages = new Iso639Language("mul","Multiple languages");
        public static readonly Iso639Language MundaLanguages = new Iso639Language("mun","Munda languages");
        public static readonly Iso639Language Creek = new Iso639Language("mus","Creek");
        public static readonly Iso639Language Mirandese = new Iso639Language("mwl","Mirandese");
        public static readonly Iso639Language Marwari = new Iso639Language("mwr","Marwari");
        public static readonly Iso639Language Mayan = new Iso639Language("myn","Mayan languages");
        public static readonly Iso639Language Erzya = new Iso639Language("myv","Erzya");
        public static readonly Iso639Language Nahuatl = new Iso639Language("nah","Nahuatl languages");
        public static readonly Iso639Language NorthAmericanIndian = new Iso639Language("nai","North American Indian languages");
        public static readonly Iso639Language Neapolitan = new Iso639Language("nap","Neapolitan");
        public static readonly Iso639Language Nauru = new Iso639Language("nau","na","Nauru");
        public static readonly Iso639Language Navajo = new Iso639Language("nav","nv","Navajo; Navaho");
        public static readonly Iso639Language SouthNdebele = new Iso639Language("nbl","nr","Ndebele, South; South Ndebele");
        public static readonly Iso639Language NorthNdebele = new Iso639Language("nde","nd","Ndebele, North; North Ndebele");
        public static readonly Iso639Language Ndonga = new Iso639Language("ndo","ng","Ndonga");
        public static readonly Iso639Language LowGerman = new Iso639Language("nds","Low German; Low Saxon; German, Low; Saxon, Low");
        public static readonly Iso639Language Nepali = new Iso639Language("nep","ne","Nepali");
        public static readonly Iso639Language NepalBhasa = new Iso639Language("new","Nepal Bhasa; Newari");
        public static readonly Iso639Language Nias = new Iso639Language("nia","Nias");
        public static readonly Iso639Language NigerKordofanian = new Iso639Language("nic","Niger-Kordofanian languages");
        public static readonly Iso639Language Niuean = new Iso639Language("niu","Niuean");
        public static readonly Iso639Language NorwegianNynorsk = new Iso639Language("nno","nn","Norwegian Nynorsk; Nynorsk, Norwegian");
        public static readonly Iso639Language NorwegianBokmal = new Iso639Language("nob","nb","Bokmål, Norwegian; Norwegian Bokmål");
        public static readonly Iso639Language Nogai = new Iso639Language("nog","Nogai");
        public static readonly Iso639Language OldNorse = new Iso639Language("non","Norse, Old");
        public static readonly Iso639Language Norwegian = new Iso639Language("nor","no","Norwegian");
        public static readonly Iso639Language NKo = new Iso639Language("nqo","N'Ko");
        public static readonly Iso639Language Pedi = new Iso639Language("nso","Pedi; Sepedi; Northern Sotho");
        public static readonly Iso639Language Nubian = new Iso639Language("nub","Nubian languages");
        public static readonly Iso639Language ClassicalNewari = new Iso639Language("nwc","Classical Newari; Old Newari; Classical Nepal Bhasa");
        public static readonly Iso639Language Chichewa = new Iso639Language("nya","ny","Chichewa; Chewa; Nyanja");
        public static readonly Iso639Language Nyamwezi = new Iso639Language("nym","Nyamwezi");
        public static readonly Iso639Language Nyankole = new Iso639Language("nyn","Nyankole");
        public static readonly Iso639Language Nyoro = new Iso639Language("nyo","Nyoro");
        public static readonly Iso639Language Nzima = new Iso639Language("nzi","Nzima");
        public static readonly Iso639Language Occitan = new Iso639Language("oci","oc","Occitan (post 1500)");
        public static readonly Iso639Language Ojibway = new Iso639Language("oji","oj","Ojibwa");
        public static readonly Iso639Language Oriya = new Iso639Language("ori","or","Oriya");
        public static readonly Iso639Language Oromo = new Iso639Language("orm","om","Oromo");
        public static readonly Iso639Language Osage = new Iso639Language("osa","Osage");
        public static readonly Iso639Language Ossetian = new Iso639Language("oss","os","Ossetian; Ossetic");
        public static readonly Iso639Language OttomanTurkish = new Iso639Language("ota","Turkish, Ottoman (1500-1928)");
        public static readonly Iso639Language Otomian = new Iso639Language("oto","Otomian languages");
        public static readonly Iso639Language Papuan = new Iso639Language("paa","Papuan languages");
        public static readonly Iso639Language Pangasinan = new Iso639Language("pag","Pangasinan");
        public static readonly Iso639Language Pahlavi = new Iso639Language("pal","Pahlavi");
        public static readonly Iso639Language Pampanga = new Iso639Language("pam","Pampanga; Kapampangan");
        public static readonly Iso639Language Panjabi = new Iso639Language("pan","pa","Panjabi; Punjabi");
        public static readonly Iso639Language Papiamento = new Iso639Language("pap","Papiamento");
        public static readonly Iso639Language Palauan= new Iso639Language("pau","Palauan");
        public static readonly Iso639Language OldPersian = new Iso639Language("peo","Persian, Old (ca.600-400 B.C.)");
        public static readonly Iso639Language PhilippineLanguages = new Iso639Language("phi","Philippine languages");
        public static readonly Iso639Language Phoenician = new Iso639Language("phn","Phoenician");
        public static readonly Iso639Language Pali = new Iso639Language("pli","pi","Pali");
        public static readonly Iso639Language Polish = new Iso639Language("pol","pl","Polish");
        public static readonly Iso639Language Pohnpeian = new Iso639Language("pon", "Pohnpeian");
        public static readonly Iso639Language Portuguese = new Iso639Language("por", "pt", "Portuguese");
        public static readonly Iso639Language Prakrit = new Iso639Language("pra", "Prakrit languages");
        public static readonly Iso639Language OldProvencal = new Iso639Language("pro", "Provençal, Old (to 1500); Occitan, Old (to 1500)");
        public static readonly Iso639Language Pushto = new Iso639Language("pus", "ps", "Pushto; Pashto");
        public static readonly Iso639Language Quechua = new Iso639Language("que", "qu", "Quechua");
        public static readonly Iso639Language Rajasthani = new Iso639Language("raj", "Rajasthani");
        public static readonly Iso639Language Rapanui = new Iso639Language("rap", "Rapanui");
        public static readonly Iso639Language Rarotongan = new Iso639Language("rar", "Rarotongan; Cook Islands Maori");
        public static readonly Iso639Language RomanceLanguages = new Iso639Language("roa", "Romance languages");
        public static readonly Iso639Language Romansh = new Iso639Language("roh", "rm", "Romansh");
        public static readonly Iso639Language Romany = new Iso639Language("rom", "Romany");
        public static readonly Iso639Language Romanian = new Iso639Language("rum", "ron", "ro", "Romanian; Moldavian; Moldovan");
        public static readonly Iso639Language Rundi = new Iso639Language("run", "rn", "Rundi");
        public static readonly Iso639Language Aromanian = new Iso639Language("rup", "Aromanian; Arumanian; Macedo-Romanian");
        public static readonly Iso639Language Russian = new Iso639Language("rus", "ru", "Russian");
        public static readonly Iso639Language Sandawe = new Iso639Language("sad", "Sandawe");
        public static readonly Iso639Language Sango = new Iso639Language("sag", "sg", "Sango");
        public static readonly Iso639Language Yakut = new Iso639Language("sah", "Yakut");
        public static readonly Iso639Language SouthAmericanIndianLanguages = new Iso639Language("sai", "South American Indian languages");
        public static readonly Iso639Language Salishan = new Iso639Language("sal", "Salishan languages");
        public static readonly Iso639Language SamaritanAramaic = new Iso639Language("sam", "Samaritan Aramaic");
        public static readonly Iso639Language Sanskrit = new Iso639Language("san", "sa", "Sanskrit");
        public static readonly Iso639Language Sasak = new Iso639Language("sas", "Sasak");
        public static readonly Iso639Language Santali = new Iso639Language("sat", "Santali");
        public static readonly Iso639Language Sicilian = new Iso639Language("scn", "Sicilian");
        public static readonly Iso639Language Scots = new Iso639Language("sco", "Scots");
        public static readonly Iso639Language Selkup = new Iso639Language("sel", "Selkup");
        public static readonly Iso639Language Semitic = new Iso639Language("sem", "Semitic languages");
        public static readonly Iso639Language OldIrish = new Iso639Language("sga", "Irish, Old (to 900)");
        public static readonly Iso639Language SignLanguages = new Iso639Language("sgn", "Sign Languages");
        public static readonly Iso639Language Shan = new Iso639Language("shn", "Shan");
        public static readonly Iso639Language Sidamo = new Iso639Language("sid", "Sidamo");
        public static readonly Iso639Language Sinhala = new Iso639Language("sin", "si", "Sinhala; Sinhalese");
        public static readonly Iso639Language Siouan = new Iso639Language("sio", "Siouan languages");
        public static readonly Iso639Language SinoTibetan = new Iso639Language("sit", "Sino-Tibetan languages");
        public static readonly Iso639Language Slavic = new Iso639Language("sla", "Slavic languages");
        public static readonly Iso639Language Slovak = new Iso639Language("slo", "slk", "sk", "Slovak");
        public static readonly Iso639Language Slovenian = new Iso639Language("slv", "sl", "Slovenian");
        public static readonly Iso639Language SouthernSami = new Iso639Language("sma", "Southern Sami");
        public static readonly Iso639Language NorthernSami = new Iso639Language("sme", "se", "Northern Sami");
        public static readonly Iso639Language SamiLanguages = new Iso639Language("smi", "Sami languages");
        public static readonly Iso639Language LuleSami = new Iso639Language("smj", "Lule Sami");
        public static readonly Iso639Language InariSami = new Iso639Language("smn", "Inari Sami");
        public static readonly Iso639Language Samoan = new Iso639Language("smo", "sm", "Samoan");
        public static readonly Iso639Language SkoltSami = new Iso639Language("sms", "Skolt Sami");
        public static readonly Iso639Language Shona = new Iso639Language("sna", "sn", "Shona");
        public static readonly Iso639Language Sindhi = new Iso639Language("snd", "sd", "Sindhi");
        public static readonly Iso639Language Sonike = new Iso639Language("snk", "Soninke");
        public static readonly Iso639Language Sogdian = new Iso639Language("sog", "Sogdian");
        public static readonly Iso639Language Somali = new Iso639Language("som", "so", "Somali");
        public static readonly Iso639Language Songhai = new Iso639Language("son", "Songhai languages");
        public static readonly Iso639Language Sotho = new Iso639Language("sot", "st", "Sotho, Southern");
        public static readonly Iso639Language Spanish = new Iso639Language("spa", "es", "Spanish; Castilian");
        public static readonly Iso639Language Sardinian = new Iso639Language("srd", "sc", "Sardinian");
        public static readonly Iso639Language Sranan = new Iso639Language("srn", "Sranan Tongo");
        public static readonly Iso639Language Serbian = new Iso639Language("srp", "sr", "Serbian");
        public static readonly Iso639Language Serer = new Iso639Language("srr", "Serer");
        public static readonly Iso639Language NiloSaharan = new Iso639Language("ssa", "Nilo-Saharan languages");
        public static readonly Iso639Language Swati = new Iso639Language("ssw", "ss", "Swati");
        public static readonly Iso639Language Sukuma = new Iso639Language("suk", "Sukuma");
        public static readonly Iso639Language Sudanese = new Iso639Language("sun", "su", "Sundanese");
        public static readonly Iso639Language Susu = new Iso639Language("sus", "Susu");
        public static readonly Iso639Language Sumerian = new Iso639Language("sux", "Sumerian");
        public static readonly Iso639Language Swahili = new Iso639Language("swa", "sw", "Swahili");
        public static readonly Iso639Language Swedish = new Iso639Language("swe", "sv", "Swedish");
        public static readonly Iso639Language ClassicalSyriac = new Iso639Language("syc", "Classical Syriac");
        public static readonly Iso639Language Syriac = new Iso639Language("syr", "Syriac");
        public static readonly Iso639Language Tahitian = new Iso639Language("tah","ty","Tahitian");
        public static readonly Iso639Language TaiLanguages = new Iso639Language("tai","Tai languages");
        public static readonly Iso639Language Tamil = new Iso639Language("tam","ta","Tamil");
        public static readonly Iso639Language Tatar = new Iso639Language("tat","tt","Tatar");
        public static readonly Iso639Language Teluga = new Iso639Language("tel","te","Telugu");
        public static readonly Iso639Language Timne = new Iso639Language("tem","Timne");
        public static readonly Iso639Language Tereno = new Iso639Language("ter","Tereno");
        public static readonly Iso639Language Tetum = new Iso639Language("tet","Tetum");
        public static readonly Iso639Language Tajik = new Iso639Language("tgk","tg","Tajik");
        public static readonly Iso639Language Tagalog = new Iso639Language("tgl","tl","Tagalog");
        public static readonly Iso639Language Thai = new Iso639Language("tha","th","Thai");
        public static readonly Iso639Language Tigre = new Iso639Language("tig","Tigre");
        public static readonly Iso639Language Tigrinya = new Iso639Language("tir","ti","Tigrinya");
        public static readonly Iso639Language Tiv = new Iso639Language("tiv","Tiv");
        public static readonly Iso639Language Tokelau = new Iso639Language("tkl","Tokelau");
        public static readonly Iso639Language Klingon = new Iso639Language("tlh","Klingon; tlhIngan-Hol");
        public static readonly Iso639Language Tlingit = new Iso639Language("tli","Tlingit");
        public static readonly Iso639Language Tamashek = new Iso639Language("tmh","Tamashek");
        public static readonly Iso639Language TongaNyasa = new Iso639Language("tog","Tonga (Nyasa)");
        public static readonly Iso639Language Tonga = new Iso639Language("ton","to","Tonga (Tonga Islands)");
        public static readonly Iso639Language TokPisin = new Iso639Language("tpi","Tok Pisin");
        public static readonly Iso639Language Tsimshian = new Iso639Language("tsi","Tsimshian");
        public static readonly Iso639Language Tswana = new Iso639Language("tsn","tn","Tswana");
        public static readonly Iso639Language Tsonga = new Iso639Language("tso","ts","Tsonga");
        public static readonly Iso639Language Turkmen = new Iso639Language("tuk","tk","Turkmen");
        public static readonly Iso639Language Tumbuka = new Iso639Language("tum","Tumbuka");
        public static readonly Iso639Language Tupi = new Iso639Language("tup","Tupi languages");
        public static readonly Iso639Language Turkish = new Iso639Language("tur","tr","Turkish");
        public static readonly Iso639Language Altaic = new Iso639Language("tut","Altaic languages");
        public static readonly Iso639Language Tuvalu = new Iso639Language("tvl","Tuvalu");
        public static readonly Iso639Language Twi = new Iso639Language("twi","tw","Twi");
        public static readonly Iso639Language Tuvian = new Iso639Language("tyv","Tuvinian");
        public static readonly Iso639Language Udmurt = new Iso639Language("udm","Udmurt");
        public static readonly Iso639Language Ugaritic = new Iso639Language("uga","Ugaritic");
        public static readonly Iso639Language Uighur = new Iso639Language("uig","ug","Uighur; Uyghur");
        public static readonly Iso639Language Ukrainian = new Iso639Language("ukr","uk","Ukrainian");
        public static readonly Iso639Language Umbundu = new Iso639Language("umb","Umbundu");
        public static readonly Iso639Language Undetermined = new Iso639Language("und","Undetermined");
        public static readonly Iso639Language Urdu = new Iso639Language("urd","ur","Urdu");
        public static readonly Iso639Language Uzbek = new Iso639Language("uzb","uz","Uzbek");
        public static readonly Iso639Language Vai = new Iso639Language("vai","Vai");
        public static readonly Iso639Language Venda = new Iso639Language("ven","ve","Venda");
        public static readonly Iso639Language Vietnamese = new Iso639Language("vie","vi","Vietnamese");
        public static readonly Iso639Language Volapuk = new Iso639Language("vol","vo","Volapük");
        public static readonly Iso639Language Votic = new Iso639Language("vot","Votic");          
        public static readonly Iso639Language Wakashan = new Iso639Language("wak","Wakashan languages");
        public static readonly Iso639Language Walaitta = new Iso639Language("wal","Wolaitta; Wolaytta");
        public static readonly Iso639Language Waray = new Iso639Language("war","Waray");
        public static readonly Iso639Language Washo = new Iso639Language("was","Washo");
        public static readonly Iso639Language Sorbian = new Iso639Language("wen","Sorbian languages");
        public static readonly Iso639Language Walloon = new Iso639Language("wln","wa","Walloon");
        public static readonly Iso639Language Wolof = new Iso639Language("wol","wo","Wolof");
        public static readonly Iso639Language Kalmyk = new Iso639Language("xal","Kalmyk; Oirat");
        public static readonly Iso639Language Xhosa = new Iso639Language("xho","xh","Xhosa");
        public static readonly Iso639Language Yao = new Iso639Language("yao","Yao");
        public static readonly Iso639Language Yapese = new Iso639Language("yap","Yapese");
        public static readonly Iso639Language Yiddish = new Iso639Language("yid","yi","Yiddish");
        public static readonly Iso639Language Yor = new Iso639Language("yor","yo","Yoruba");
        public static readonly Iso639Language Yupik = new Iso639Language("ypk","Yupik languages");
        public static readonly Iso639Language Zapotec = new Iso639Language("zap","Zapotec");
        public static readonly Iso639Language Bliss = new Iso639Language("zbl","Blissymbols; Blissymbolics; Bliss");
        public static readonly Iso639Language Zenaga = new Iso639Language("zen","Zenaga");
        public static readonly Iso639Language Zhuang = new Iso639Language("zha","za","Zhuang; Chuang");
        public static readonly Iso639Language Zande = new Iso639Language("znd","Zande languages");
        public static readonly Iso639Language Zulu = new Iso639Language("zul","zu","Zulu");
        public static readonly Iso639Language Zuni = new Iso639Language("zun","Zuni");
        public static readonly Iso639Language NotApplicable = new Iso639Language("zxx","No linguistic content; Not applicable");
        public static readonly Iso639Language Zaza = new Iso639Language("zza", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki");

        #endregion
    }
}
